In [50]:
import pandas as pd

def audit_report(df):
    print("**************************AUDIT REPORT***********************")
    print ("-----------------Number of Columns--------------------------")
    print(len(df.columns))
    print ("-----------------Number of Records--------------------------")
    print(len(df.index))
    print ("-----------------Columns Data Types-------------------------")
    print(df.dtypes)
    print ("-----------------Number of Missing cells--------------------")
    print(df.isnull().sum())
    print ("-----------------Number of duplicate rows--------------------")    
    print(df.duplicated().sum())
    print ("-----------------Memory Taken By Dataframe-------------------") 
    print((df.memory_usage(deep=True).sum())/1048576, "MB" )
    print ("-----------------------Warning-------------------------------")
    print("Max missing values are in column:",df.count().idxmin())
    print ("-------------------Range of columns--------------------------")
    print(df.describe().loc[['max','min']])
    print("--------------------Unique Classes in columns-----------------")
    for i in df:
        if(df[i].dtypes=="object"):
            print( df[i].unique())
        
    return;

In [51]:
def main_function():
    user_file_name= input("Enter full file path")
    df=pd.read_excel(user_file_name)
    audit_report(df)
    merge_columns(df, df['province'], df['region'])
    return;

In [52]:
main_function()

Enter full file pathC:/Users/Zohran/Documents/R/sec_b.xlsx
**************************AUDIT REPORT***********************
-----------------Number of Columns--------------------------
20
-----------------Number of Records--------------------------
513961
-----------------Columns Data Types-------------------------
hhcode        int64
psu           int64
province     object
region       object
district     object
sec          object
idc           int64
sbq02        object
sbq03        object
sbq04        object
sbq05        object
sbq61         int64
sbq62         int64
sbq63         int64
age           int64
sbq07        object
sbq08       float64
sbq09         int64
sbq10         int64
sbq11        object
dtype: object
-----------------Number of Missing cells--------------------
hhcode           0
psu              0
province         0
region           0
district         0
sec              0
idc              0
sbq02            0
sbq03        78642
sbq04            0
sbq05            0
sbq61            0
sbq62            0
sbq63            0
age              0
sbq07            0
sbq08       321765
sbq09            0
sbq10            0
sbq11            0
dtype: int64
-----------------Number of duplicate rows--------------------
16
-----------------Memory Taken By Dataframe-------------------
358.49631690979004 MB
-----------------------Warning-------------------------------
Max missing values are in column: sbq08
-------------------Range of columns--------------------------
           hhcode         psu   idc   sbq61  sbq62  sbq63   age  sbq08  sbq09  \
max  6.112301e+09  61123008.0  60.0  2015.0   12.0   31.0  99.0   99.0   99.0
min  1.111000e+09  11110001.0   1.0  1894.0    0.0    0.0   0.0    1.0    1.0

     sbq10
max   99.0
min    1.0
--------------------Unique Classes in columns-----------------
['kp' 'punjab' 'sindh' 'balochistan']
['rural' 'urban']
['chitral' 'upper dir' 'lower dir' 'swat' 'shangla' 'buner' 'malakand'
 'kohistan' 'mansehra' 'batagram' 'abbottabad' 'haripur' 'tor ghar'
 'mardan' 'swabi' 'charsadda' 'peshawar' 'nowshera' 'kohat' 'hangu'
 'karak' 'bannu' 'lakki marwat' 'd. i. khan' 'tank' 'attock' 'rawalpindi'
 'jhelum' 'chakwal' 'sargodha' 'bhakkar' 'khushab' 'mianwali' 'faisalabad'
 'chiniot' 'jhang' 't.t. singh' 'gujranwala' 'hafizabad' 'gujrat'
 'mandi bahauddin' 'sialkot' 'narowal' 'lahore' 'kasur' 'sheikhupura'
 'nankana sahib' 'okara' 'sahiwal' 'pakpattan' 'vehari' 'multan' 'lodhran'
 'khanewal' 'd. g. khan' 'rajanpur' 'layyah' 'muzaffargarh' 'bahawalpur'
 'bahawalnagar' 'rahim yar khan' 'jacobabad' 'kashmore' 'shikarpur'
 'larkana' 'shahdadkot' 'sukkur' 'ghotki' 'khairpur' 'naushahro feroze'
 'shaheed benazir abad' 'dadu' 'jamshoro' 'hyderabad' 'tando allah yar'
 'tando mohammad khan' 'matiari' 'badin' 'thatta' 'sujawal' 'sanghar'
 'mirpur khas' 'umer kot' 'tharparkar' 'karachi' 'quetta' 'pishin'
 'killa abdullah' 'chagai' 'nushki' 'loralai' 'barkhan' 'musakhel'
 'killa saifullah' 'zhob' 'sheerani' 'sibbi' 'harnai' 'ziarat' 'kohlu'
 'dera bugti' 'bolan/ kachhi' 'jaffarabad' 'nasirabad/ tamboo'
 'jhal magsi' 'kalat' 'mastung' 'khuzdar' 'awaran' 'kharan' 'washuk'
 'lasbela' 'gwadar' 'islamabad']
['00B']
['head' 'spouse' 'son/daughter' 'son/daughter-in-law' 'grand child'
 'brother/sister-in-law' 'nephew\\niece' 'father/mother' 'brother\\sister'
 'uncle/aunty' 'father/mother-in-law' 'others' 'grand father/mother'
 'servants/their relatives']
[nan 'family elder' 'main provider away for work' 'main economic provider'
 'is oldest male in the house?' 'others']
['male' 'female']
['present' 'temporarily absent at the time of enumeration']
['currently married' 'unmarried/never married' 'widow/widower'
 'nikah has been solemnised but the rukhsati has  not taken place'
 'divorced']
['yes' 'no']
type should be numeric

In [53]:
def my_add(c1,c2):
    return (c1+c2)

def my_subtract(c1,c2):
    return (c1-c2)

def my_multiply(c1,c2):
    return (c1*c2)

def my_divide(c1,c2):
    return c1/c2


def merge_columns(df, col_name1, col_name2):
    if(col_name1.dtypes != "object" and col_name2.dtypes != "object" ):
        print("Press 1 for addition")
        print("Press 2 for subtraction")
        print("Press 3 for division")
        print("Press 4 for multiplication")
        option = input("Enter your choice: ")
        
        if(option=='1'):
            new_col=my_add(col_name1, col_name2)
            df['add_operation']=new_col
            print(df.head())
        elif(option=='2'):
            new_col=my_subtract(col_name1, col_name2)
            df['subtract_operation']=new_col
            print(df.head())
        elif(option=='3'):
            new_col=my_multiply(col_name1, col_name2)
            df['multiply_operation']=new_col
            print(df.head())
        elif(option=='4'):
            new_col=my_divide(col_name1, col_name2)
            df['divide_operation']=new_col
            print(df.head())
        else:
            print("Wrong Input")
    else:
        print("Error: Type should be numeric")